rules:
  no-vendor-prefixes: 0
  single-line-per-selector: 0
  nesting-depth:
    - 1
    - max-depth: 4
  leading-zero:
    - 1
    - include: true
  no-misspelled-properties:
    - 1
    - extra-properties:
      - osx-font-smoothing
      - overflow-scrolling
  property-sort-order:
    - 1
    - order:
      - flex
      - flex-grow
      - flex-shrink
      - flex-basis
      -
      - display
      -
      - flex-flow
      - flex-wrap
      - flex-direction
      -
      - justify-content
      -
      - align-items
      - align-self
      - align-content
      -
      - position
      - top
      - right
      - bottom
      - left
      -
      - width
      - min-width
      - max-width
      -
      - height
      - min-height
      - max-height
      -
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      -
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      -
      - float
      - clear
      -
      - columns
      - column-count
      - column-fill
      - column-gap
      - column-rule
      - column-span
      - column-width
      -
      - transform
      - transform-origin
      -
      - transition
      - transition-delay
      - transition-duration
      - transition-property
      - transition-timing-function
      -
      - # Border
      - border
      - border-top
      - border-right
      - border-bottom
      - border-left
      -
      - border-width
      - border-top-width
      - border-right-width
      - border-bottom-width
      - border-left-width
      -
      - border-style
      - border-top-style
      - border-right-style
      - border-bottom-style
      - border-left-style
      -
      - border-radius
      - border-top-left-radius
      - border-top-right-radius
      - border-bottom-left-radius
      - border-bottom-right-radius
      -
      - border-color
      - border-top-color
      - border-right-color
      - border-bottom-color
      - border-left-color
      -
      - outline
      - outline-color
      - outline-offset
      - outline-style
      - outline-width
      -
      - # Text
      - color
      -
      - font
      - font-family
      - font-feature-settings
      - font-size
      - font-smoothing
      - font-style
      - font-variant
      - font-weight
      -
      - letter-spacing
      - line-height
      - list-style
      -
      - text-align
      - text-decoration
      - text-indent
      - text-overflow
      - text-rendering
      - text-shadow
      - text-transform
      - text-wrap
      -
      - white-space
      - word-spacing
      -
      - # Background
      - background
      - background-attachment
      - background-blend-mode
      - background-color
      - background-image
      - background-position
      - background-repeat
      - background-size
      -
      - # Other
      - border-collapse
      - border-spacing
      - box-shadow
      - caption-side
      - content
      - cursor
      - empty-cells
      - opacity
      - overflow
      - overflow-x
      - overflow-y
      - quotes
      - speak
      - table-layout
      - user-select
      - vertical-align
      - visibility
      - z-index
